### ISSUE TITLE
Calling next on a node recursively results in a Null

### ISSUE THREAD

**Issue by Gummby** [tuelsch/ts-linked-list#33]
Hi there,

not sure if this something I am doing wrong, but I can not seem to figure it out. I am building a linked list using the static from method. After that I then recursively call .next to step through my list. Reason I am doing this is it's a carousel that at any moment I can append a node and not have to restart the carousel.

If I log the node out this is what follows:
```
{
    "data": {  // head node
        "path": "slide1",
        "duration": "10000"
    },
    "prev": null, // should be pointing to tail
    "next": {
        "data": {
            "path": "slide2",
            "duration": "10000"
        },
        "prev": "[Circular]",
        "next": {
            "data": {
                "path": "slide3",
                "duration": "10000"
            },
            "prev": "[Circular]",
            "next": null, // should be pointing to head
            "list": {
                "head": "[Circular]",
                "tail": "[Circular]",
                "size": 3
            }
        },
        "list": "[Circular]"
    },
    "list": "[Circular]"
}

```

It seems to have some broken links with the head and tail.

**Comment by tuelsch** [comment]
hey @Gummby, the linked list is generally not circular, so the first element, the head, should have a null reference as prev. Also, the tail should have a null reference as next.

You could cycle through the list by checking for null like:
```js
const nextItem = currentItem.next || list.head;
```

**Comment by Gummby** [comment]
> hey @Gummby, the linked list is generally not circular, so the first element, the head, should have a null reference as prev. Also, the tail should have a null reference as next.
> 
> You could cycle through the list by checking for null like:
> 
> ```js
> const nextItem = currentItem.next || list.head;
> ```

Hi @tuelsch that makes sense. I was a little thrown by the circular references in the log so I just assumed it was. I am currently doing something similar to your suggestion, its good to know I was implementing it wrong. Thanks :)
