### ISSUE TITLE
Feature request: Export types for LinkedListNode, TMapFunction and TTestFunction

### ISSUE THREAD

**Issue by jaames** [tuelsch/ts-linked-list#44]
Hey there! Great work on this library!

I was wondering if it would be possible to export the types for `LinkedListNode`, `TMapFunction` and `TTestFunction` along with the default `LinkedList` export. I have a situation where I want to keep a reference to a particular node in the linked list, and being able to type that to `LinkedListNode` would be really handy. It doesn't look like that's currently possible because this library doesn't export the `LinkedListNode` type?

Would be happy to submit a PR for this. Cheers!

**Comment by tuelsch** [comment]
Hey @jaames, that's a great idea. I'd be happy to get your PR!
